MoviesWeb/Controllers/GenreController.cs
using MoviesWeb.ViewModels;
using PL.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MoviesWeb.Controllers
{
    public class GenreController : Controller
    {
            private MovieContext db = new MovieContext();

            // GET: Genre
            public ActionResult Index()
            {
                var genres = db.Genres.OrderBy(g => g.Name);
                return View(genres.ToList());
            }

            public ActionResult About()
            {
                var data = from movie in db.Movies
                           group movie by movie.Genre into dateGroup
                           select new GenreDataInfo()
                           {
                               GenreName = dateGroup.Key.Name,
                               GenreCount = dateGroup.Count(),
                               TotalGross = dateGroup.Sum(m => m.Gross),
                               AverageRating = dateGroup.Average(m => m.Rating)
                           };
                return View(data.OrderByDescending(g => g.GenreCount).ToList());
            }

            protected override void Dispose(bool disposing)
            {
                db.Dispose();
                base.Dispose(disposing);
            }
        }

    }

MoviesWeb/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PL.Models;

namespace MoviesWeb.Controllers
{
    public class MovieController : Controller
    {
        private MovieContext db = new MovieContext();

        // GET: Movie
        //public ActionResult Index()
        //{
        //    var movies = db.Movies.Include(m => m.Genre);
        //    return View(movies.ToList());
        //}
        public ViewResult Index(string searchString, string sortOrder, int? SelectedGenre)
        {
            var genres = db.Genres.OrderBy(g => g.Name).ToList();
            ViewBag.SelectedGenre = new SelectList(genres, "GenreID", "Name", SelectedGenre);
            int genreID = SelectedGenre.GetValueOrDefault();

            var movies = db.Movies
                .Where(c => !SelectedGenre.HasValue || c.GenreID == genreID);

            //var movies = from movie in movieDb.Movies
            //               select movie;

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Title.Contains(searchString));
            }

            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "rating_asc" : "";
            ViewBag.RatingSortParm = sortOrder == "Rating" ? "rating_asc" : "rating_desc";

            switch (sortOrder)
            {
                case "rating_desc":
                    movies = movies.OrderByDescending(s => s.Rating);
                    break;
                case "rating_asc":
                    movies = movies.OrderBy(s => s.Rating);
                    break;
            }

            return View(movies);
        }


        // GET: Movie/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // GET: Movie/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Name");
            return View();
        }

        // POST: Movie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LogAttribute]
        public ActionResult Create([Bind(Include = "ID,Title,Director,ReleaseDate,Gross,Rating,GenreID")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Name", movie.GenreID);
            return View(movie);
        }

        // GET: Movie/Edit/5
        [Authorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Name", movie.GenreID);
            return View(movie);
        }

        // POST: Movie/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //[LogAttribute]
        //public ActionResult Edit([Bind(Include = "ID,Title,Director,ReleaseDate,Gross,Rating,GenreID")] Movie movie)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(movie).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Name", movie.GenreID);
        //    return View(movie);
        //}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LogAttribute]
        public ActionResult Edit(int id, string title, string director,
                                 DateTime releaseDate, decimal gross,
                                 double rating, string imageUrl, int genreID,
                                 HttpPostedFileBase image)

        {
            var movie = db.Movies.Find(id);
            if (ModelState.IsValid && movie != null)
            {
                movie.Title = title;
                movie.Director = director;
                movie.ReleaseDate = releaseDate;
                movie.Gross = gross;
                movie.Rating = rating;
                movie.ImageUrl = imageUrl;
                movie.GenreID = genreID;
                //if image object is not empty update the photo attribute, using image info.
                if (image != null)
                {
                    movie.ImageMimeType = image.ContentType;
                    movie.ImageFile = new byte[image.ContentLength];
                    //save the photo file by using image.InputStream.Read method.
                    image.InputStream.Read(movie.ImageFile, 0, image.ContentLength);
                }
                
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GenreID = new SelectList(db.Genres, "GenreID", "Name", movie.GenreID);
            return View(movie);
        }

        // GET: Movie/Delete/5
        [Authorize(Users = "admin@psa.br")]
        [LogAttribute]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        // POST: Movie/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "admin@psa.br")]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
       // [Authorize(Users = "admin@psa.br")]
        public ActionResult RemoveAjax(int id)
        {
            var movie = db.Movies.Find(id);
            if (movie == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            string movieName = movie.Title;

            db.Movies.Remove(movie);
            db.SaveChanges();

            var results = new
            {
                Message = movieName + "has been removed.",
                DeleteId = id
            };
            return Json(results);

        }



        public ActionResult Browse(string genre = "Action")
        {
            var genreModel = db.Genres.Include("Movies").Single(g => g.Name == genre);

            return View(genreModel);
        }

        public ActionResult GetImage(int id)
        {
            Movie movie = db.Movies.Find(id);
            if (movie != null && movie.ImageFile != null)
            {
                return File(movie.ImageFile, movie.ImageMimeType);
            }
            else
            {
                return new FilePathResult("~/Images/nao-disponivel.jpg", "image/jpeg");
            }
        }


        public ActionResult Catalogo(string titulo)
        {
            string filePath = Server.MapPath("~/Content/Catalogo/") + titulo.ToLower() + ".pdf";

            if (System.IO.File.Exists(filePath))
                return new FilePathResult(filePath, "application/pdf");
            else
                return HttpNotFound();
        }


        public JsonResult Filmes()
        {
            // atenção: este código é apenas um exemplo;
            // ver possíveis vulnerabilidades em:
            // http://msdn.microsoft.com/query/dev11.query?appId=Dev11IDEF1&l=EN-US&k=k(System.Web.Mvc.JsonRequestBehavior);k(TargetFrameworkMoniker-.NETFramework,Version%3Dv4.5);k(DevLang-csharp)&rd=true
            // http://haacked.com/archive/2008/11/20/anatomy-of-a-subtle-json-vulnerability.aspx
            // http://msdn.microsoft.com/en-us/library/hh404095.aspx

            var model = from movie in db.Movies
                        select new
                        {
                            Titulo = movie.Title,
                            Ano = movie.ReleaseDate.Year,
                            Genero = movie.Genre.Name,
                            Avaliacao = movie.Rating
        };
           return Json(model.OrderBy(m => m.Ano), JsonRequestBehavior.AllowGet);
        }

        [Authorize(Users = "admin@psa.br")]
        public ActionResult ViewLog()
        {
            var logs = db.Logs;
            return View(logs.ToList());
        }

        [ChildActionOnly]
        public ActionResult GenreMenu(int num = 5)
        {
            var genres = db.Genres
                               .OrderByDescending(g => g.Movies.Count)
                               .Take(num)
                               .ToList();

            return this.PartialView(genres);
        }

        public ActionResult MovieFilter(string term)
        {
            term = term.ToLower();

MoviesWeb/Views/Movie/Browse.cshtml
@model PL.Models.Genre

@{
    ViewBag.Title = "Browse";
}

<h2>Browse</h2>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

    </dl>
</div>
<div>
    <ul id="album-list">
        @foreach (var item in Model.Movies)
        {
            <li>
                @Html.ActionLink(item.Title, "Details", new { ID = item.ID })
            </li>
        }
    </ul>
</div>

MoviesWeb/Views/Movie/Create.cshtml
@model PL.Models.Movie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gross, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gross, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gross, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
           $(function() {
            $( "#ReleaseDate" ).datepicker({
              showOn: "button",
              buttonImage: "../../images/calendar.gif",
              buttonImageOnly: true,
              buttonText: "Select date"
            });
          });
    </script>

}

MoviesWeb/Views/Movie/Delete.cshtml
@model PL.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gross)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gross)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MoviesWeb/Views/Movie/Details.cshtml
@model PL.Models.Movie

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Director)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Director)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gross)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gross)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

    </dl>
</div>


<img width="200" src="@Url.Action("GetImage", "Movie", new { id=Model.ID})" />

@if (Model.ImageUrl != null)
{
    <img width="200" src="@Model.ImageUrl" alt=@Model.Title>
}
else
{
    @: ulr image not available
}





<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MoviesWeb/Views/Movie/Edit.cshtml
@model PL.Models.Movie

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@*using (Html.BeginForm())*@
@using (Html.BeginForm("Edit", 
                        "Movie",
                        FormMethod.Post,
                        new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Movie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Director, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Director, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gross, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gross, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gross, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl,
                      htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Image" />
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script>
           $(function() {
            $( "#ReleaseDate" ).datepicker({
              showOn: "button",
              buttonImage: "../../images/calendar.gif",
              buttonImageOnly: true,
              buttonText: "Select date"
            });
          });
    </script>

}

MoviesWeb/Views/Movie/GenreMenu.cshtml
@model IEnumerable<PL.Models.Genre>

<div class="container">

    <div class="btn-group btn-group-justified">
        @foreach (var genre in Model)
        {

            @Html.ActionLink(genre.Name,
                    "Browse", "Movie",
                    new { Genre = genre.Name }, new { @class = "btn btn-primary" })  }
        @Html.ActionLink("More...", "Index", "Genre", null, new { @class = "btn btn-primary" })
    </div>
</div>

MoviesWeb/Views/Movie/Index.cshtml
@model IEnumerable<PL.Models.Movie>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        Find by name or director: @Html.TextBox("SearchString")
        <input type="submit" value="Search" />
        Select Genre: @Html.DropDownList("SelectedGenre", "All")
        <input type="submit" value="Filter" />
    </p>
}

<!--table class="table">-->
<table class="table table-striped table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Director)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gross)
        </th>
        <th>
            @*@Html.DisplayNameFor(model => model.Rating)*@
            @Html.ActionLink("Rating", "Index", new { sortOrder = ViewBag.RatingSortParm })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gross)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "label label-warning" }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "label label-info" }) |
               @* @Html.ActionLink(" ", "Delete", new { id = item.ID }, new { @class = "btn btn-danger deleteBtn  btn-xs glyphicon glyphicon-trash" })*@
                @Html.ActionLink(" ",
                      "Delete",
                      new { id = item.ID },
                      new
                      {
                          data_id = @item.ID,
                          @class = "RemoveLink btn btn-danger deleteBtn  btn-xs glyphicon glyphicon-trash"
                      })




            </td>
        </tr>
    }

    </table>

<div hidden id="delete-dialog" title="Confirmação de remoção">
    <p>Deseja realmente apagar este filme?</p>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")

    <script type="text/javascript">
        var deleteLinkObj;
        var recordToDelete;
        $(document).ready(function () {
            $('.RemoveLink').click(function () {
                deleteLinkObj = $(this);
                recordToDelete = $(this).attr("data-id");
                $('#delete-dialog').dialog('open');
                return false;
            })
        });

        $('#delete-dialog').dialog({
            autoOpen: false, width: 400, resizable: false,
            modal: true, dialogClass: 'button',
            buttons: {
                "Continue": function () {
                    $.post("/Movie/RemoveAjax", { "id": recordToDelete })
                       .done(function (data) {
                           alert(data.Message);
                           deleteLinkObj.closest("tr").hide('fast');
                       })
                       .fail(function () {
                           alert("erro!");
                       });
                    $(this).dialog("close");
                },
                "Cancel": function () {
                    $(this).dialog("close");
                }
            }
        });
      </script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#SearchString').autocomplete({
                source: '@Url.Action("MovieFilter")'
            });
        })

</script>

    <script src=http://ajax.aspnetcdn.com/ajax/jquery.ui/1.9.2/jquery-ui.min.js type="text/javascript">
    </script>

    
    
 }

MoviesWeb/Views/Movie/ViewLog.cshtml
@model IEnumerable<PL.Models.Log>

@{
    ViewBag.Title = "ViewLog";
}

<h2>ViewLog</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.OperationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Action)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.OperationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Action)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
    
    </tr>
}

</table>